import React, { useEffect, useState } from "react";
import Footer from "../../components/Footer";
import Header from "../../components/Header";
import Head from "next/dist/shared/lib/head";
import { useRouter } from "next/router";
import axios from "axios";
import { APIkey } from "../../common/apis/tmdbApiKey";
import Card from "../../components/Card";
import PosterCard from "../../components/PosterCard";
const Search = () => {
  const router = useRouter();
  const SearchTerm = router.query.searchTerm;
  const [data, setData] = useState({});
  useEffect(() => {
    axios
      .get(
        `https://api.themoviedb.org/3/search/movie?api_key=${APIkey}&language=en-US&query=${SearchTerm}&page=1&include_adult=false`
      )
      .then((response) => {
        console.log(response);
        setData(response);
      });
  }, [SearchTerm]);
  if (data.status === 200 && data.data.total_results === 0) {
    return (
      <>
        <Head>
          <title>Search results for {SearchTerm}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Header />
          <div className="flex flex-col   sm:p-0 container mx-auto justify-center items-center h-screen">
            <div>
              <img className=" w-[350px]" src="/nodata.svg" alt="" />
            </div>
            <div className="  font-medium px-5 mt-20">
              There are no results for '{SearchTerm}' are you sure you searched
              for the right movie?
            </div>
          </div>
          <Footer />
        </div>
      </>
    );
  }
  if (data.status !== 200) {
    return (
      <>
        <Header />
        <div className=" h-screen w-screen flex justify-center items-center">
          <div>
            <button className="btn loading">loading</button>
          </div>
        </div>
      </>
    );
  }
  return (
    <>
      <Head>
        <title>Search results for {SearchTerm}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <div className="  sm:p-0 container mx-auto">
          <div className=" mt-20 font-normal text-lg text-center ">
            Search results for{" "}
            <span className=" font-medium bg-secondary px-1 rounded-md">
              {SearchTerm}
            </span>
          </div>
          <div className="  flex justify-center gap-5 flex-wrap">
            {data.status === 200 &&
              data.data.results.map((res) => (
                <PosterCard key={res.id} res={res} />
              ))}
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
};

export default Search;
