import React, { useEffect } from "react";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Head from "next/head";
import { useRouter } from "next/router";
import axios from "axios";
import {
  fetchAsyncMoviesOrShowsDetail,
  getSelectedMovieOrShow,
} from "../features/data/movieSlice";
import { useDispatch, useSelector } from "react-redux";
import DetailComponent from "../components/DetailComponent";

const DetailsInfo = () => {
  const router = useRouter();
  const tmdbId = router.query.tmdbId;
  console.log(tmdbId);
  const data = useSelector(getSelectedMovieOrShow);
  const dispatch = useDispatch();
  console.log(data);
  useEffect(() => {
    dispatch(fetchAsyncMoviesOrShowsDetail(tmdbId));
  }, [tmdbId]);
  console.log(data);
  return (
    <>
      <Head>
        <title>{data.status === 200 && data.data.title} - MovieDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <div className="  sm:p-0 container mx-auto mt-10">
          <DetailComponent data={data} />
        </div>
        <Footer />
      </div>
    </>
  );
};

export default DetailsInfo;
