import React, { useEffect, useState } from "react";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Head from "next/head";
import { useRouter } from "next/router";
import axios from "axios";
import {
  fetchAsyncMoviesOrShowsDetail,
  getSelectedMovieOrShow,
} from "../features/data/movieSlice";
import { useDispatch, useSelector } from "react-redux";
import DetailComponent from "../components/DetailComponent";
import { APIkey } from "../common/apis/tmdbApiKey";

const DetailsInfo = () => {
  const router = useRouter();
  const tmdbId = router.query.tmdbId;
  const [data, setData] = useState({});
  console.log(tmdbId);

  useEffect(() => {
    axios
      .get(
        `https://api.themoviedb.org/3/movie/${tmdbId}?api_key=${APIkey}&language=en-US`
      )
      .then((response) => {
        console.log(response);
        setData(response);
      });
  }, [tmdbId]);

  if (data.status !== 200) {
    return (
      <>
        <Header />
        <div className=" h-screen w-screen flex justify-center items-center">
          <div>
            <button class="btn loading">loading</button>
          </div>
        </div>
      </>
    );
  }
  return (
    <>
      <Head>
        <title>{data.status === 200 && data.data.title} - MovieDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <div className="  sm:p-0 container mx-auto mt-10">
          <DetailComponent data={data} />
        </div>
        <Footer />
      </div>
    </>
  );
};

export default DetailsInfo;
