import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import TrendingSection from "../components/TrendingSection";
import { useDispatch, useSelector } from "react-redux";
import { useEffect, useState } from "react";
import { fetchAsyncTrending, getTrending } from "../features/data/movieSlice";
import Footer from "../components/Footer";
import { useUserContext } from "../context/userContext";
import { BASEIMAGEURL } from "../common/apis/tmdbApiKey";
export default function Detail() {
  const [realData, setRealData] = useState({});
  const dispatch = useDispatch();
  const { Id, setId } = useUserContext();
  console.log(Id);
  useEffect(() => {
    dispatch(fetchAsyncTrending());
  }, [dispatch]);

  const trending = useSelector(getTrending);
  useEffect(() => {
    const data = trending.results;
    const obj = data.find((x) => x.id == Id);
    setRealData(obj);
  }, [trending]);

  return (
    <>
      <Head>
        <title>Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <div className=" mt-20  sm:p-0 container mx-auto">
          <div className="hero min-h-screen bg-base-200">
            <div className="hero-content flex-col lg:flex-row-reverse">
              <img
                src={`${BASEIMAGEURL}${realData.poster_path}`}
                className="max-w-sm rounded-lg shadow-2xl"
              />
              <div>
                <h1 className="text-5xl font-bold">{realData.title}</h1>
                <p className="py-6">{realData.overview}</p>
                <button className="btn btn-primary">Get Started</button>
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
}
